defaults:
  limit: 100
  period: "week"

  reddit:
    subreddits:
      - cryptocurrency
      - CryptoMarkets
      - bitcoin
      - ethereum
      - altcoin

  telegram:
    channels:
      - Coin_Post
      - cryptonarratives1
      - CryptoRankNews
      - CryptoWorldNews
      - top7ico
      - bitcoin
